#~~~~~~~~~~~
## Converts the tables generated by R (xtable) into a word document
#~~~~~~~~~~~
## Requires: pandoc!

CI=$1

## Generate the LaTeX temp
echo "\documentclass{article}" > table_result.temp
echo "\\\begin{document}"  >> table_result.temp
echo ""  >> table_result.temp

for tex in *.tex
do
    prefix=$(basename ${tex} _${CI}.tex | sed 's/_/ /g')
    echo "\section{${prefix}}" >> table_result.temp
    echo "\input{${tex}}" >> table_result.temp
    echo ""  >> table_result.temp
done

echo "\end{document}" >> table_result.temp

mv table_result.temp table_result.tex

## Convert into docx
pandoc -i table_result.tex -o result_table_${CI}.docx

## Cleaning
rm table_result.tex
