---
title: "Landmark region difference (data)"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

```{r}
## Loading the libraries (and installing if necessary)
if(!require(geomorph)) install.packages("geomorph")
```

This script reads in the data and saves it in the proper format to be analysed

## Inputs

The data should be stored in `../Data/` in the following format:

Data type | Data set | Species | File format
----------|----------|---------|------------
landmarkdata | cranium  | wombat | .csv
landmarkgroups | mandible | koala |



### Data per genus

```{r}
## The chain names
chains <- c("wombat", "koala")

## The datasets
datasets <- c("cranium", "mandible")

## Looping through the chains
for(chain in chains) {
    
    ## Output list holder
    land_data <- list()

    ## Looping through the datasets
    for(dataset in datasets) {

        ## Read the landmarks groups
        land_data[[dataset]][[1]] <- read.csv(paste0("../Data/landmarkgroups_", dataset, "_",
                                                chain, ".csv"))
        
        ## Read the landmarks
        land_data[[dataset]][[2]] <- t(read.csv(paste0("../Data/landmarkdata_", dataset, "_",
                                                  chain, ".csv") , header = TRUE, row.names = 1))
        
        ## Remove any NAs rows
        land_data[[dataset]][[2]] <- land_data[[dataset]][[2]][complete.cases(
                                                                   land_data[[dataset]][[2]]),]
        
        ## Make into a 3D array
        land_data[[dataset]][[2]] <- geomorph::arrayspecs(land_data[[dataset]][[2]], k = 3,
                                                            p = ncol(land_data[[dataset]][[2]])/3)

        ## Running the Procrustes superimposition
        land_data[[dataset]][[3]] <- geomorph::gpagen(land_data[[dataset]][[2]],
                                                        print.progress = FALSE)

        ## Convert the array in 2D
        array_2d <- geomorph::two.d.array(land_data[[dataset]][[3]]$coords)

        ## measure the tolerance
        tol <- prcomp(array_2d)$sdev^2
        tolerance <- cumsum(tol)/sum(tol)
        tolerance <- length(which(tolerance < 1)) 
        if(length(tolerance) < length(tol)){
            tolerance <- tolerance + 1
        }
        tolerance <- max(c(tol[tolerance]/tol[1],0.005))

        ## Ordinating the data
        land_data[[dataset]][[4]] <- prcomp(array_2d, center = TRUE, scale. = FALSE, retx = TRUE,
                                              tol = tolerance)

        ## Name the elements
        names(land_data[[dataset]]) <- c("landmarkgroups", "landmarkdata", "procrustes",
                                           "ordination")
    }

    ## Save the file
    save(land_data, file = paste0("../Data/Processed/", chain, ".Rda"))
}
```

### Data per species

```{r}
## Selecting the wombats
chain <- chains[1]

## Getting the species names
species <- c("ursinus", "latifrons", "krefftii")
sp_holders <- c("Common wombat", "SHN wombat", "NHN wombat")

## Reading the wombat species
wombat_sp <- read.csv("../Data/wombat_species.csv")
for(sp in 1:length(species)) {
    wombat_sp$Species <- gsub(sp_holders[sp], species[sp], as.character(wombat_sp$Species))
}

land_data <- list()

for(sp in 1:length(species)) {

    for(dataset in datasets) {

        ## Read the landmarks groups
        land_data[[dataset]][[1]] <- read.csv(paste0("../Data/landmarkgroups_", dataset, "_",
                                                chain, ".csv"))
        
        ## Read the landmarks
        land_data[[dataset]][[2]] <- t(read.csv(paste0("../Data/landmarkdata_", dataset, "_",
                                                  chain, ".csv") , header = TRUE, row.names = 1))
        
        ## Remove any NAs rows
        land_data[[dataset]][[2]] <- land_data[[dataset]][[2]][complete.cases(
                                                                   land_data[[dataset]][[2]]),]
        
        ## Make into a 3D array
        land_data[[dataset]][[2]] <- geomorph::arrayspecs(land_data[[dataset]][[2]], k = 3,
                                                            p = ncol(land_data[[dataset]][[2]])/3)

        ## Selecting the subset of species
        land_data[[dataset]][[2]] <- land_data[[dataset]][[2]][, , which(wombat_sp$Species == species[sp])]

        ## Procrustes superimposition
        land_data[[dataset]][[3]] <- geomorph::gpagen(land_data[[dataset]][[2]],
                                                        print.progress = FALSE)

        ## Convert the array in 2D
        array_2d <- geomorph::two.d.array(land_data[[dataset]][[3]]$coords)

        ## measure the tolerance
        tol <- prcomp(array_2d)$sdev^2
        tolerance <- cumsum(tol)/sum(tol)
        tolerance <- length(which(tolerance < 1)) 
        if(length(tolerance) < length(tol)){
            tolerance <- tolerance + 1
        }
        tolerance <- max(c(tol[tolerance]/tol[1],0.005))

        ## Ordinating the data
        land_data[[dataset]][[4]] <- prcomp(array_2d, center = TRUE, scale. = FALSE, retx = TRUE,
                                              tol = tolerance)

        ## Name the elements
        names(land_data[[dataset]]) <- c("landmarkgroups", "landmarkdata", "procrustes",
                                           "ordination")
    }

    save(land_data, file = paste0("../Data/Processed/", chain, "_", species[sp], ".Rda"))
}
```