---
title: "Landmark region difference"
author: "Thomas Guillerme"
bibliography: references.bib
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

```{r, message = FALSE, warning = FALSE}
## Loading the libraries (and installing if necessary)
if(!require(devtools)) install.packages("devtools")
if(!require(knitr)) install.packages("knitr")
if(!require(geomorph)) install.packages("geomorph")
if(!require(RCurl)) install.packages("RCurl")
if(!require(zoo)) install.packages("zoo")
if(!require(dispRity)) install_github("dispRity")
## Loading the function
source("../Functions/coordinates.difference.R")
source("../Functions/coordinates.area.R")
source("../Functions/variation.range.R")
source("../Functions/rand.test.R")
source("../Functions/area.diff.R")
source("../Functions/sanitizing.R")
source("../Functions/utilities.R")
set.seed(1)
```

# Within species

## Wombat ursinus

### Cranium

```{r, fig.width = 10, fig.height = 15, echo = FALSE, message = FALSE}
results <- pipeline.test("Wombat_ursinus", "cranium", "../Data/Processed/", verbose = TRUE)

caption_diff <- paste0("Results of the area difference random test for the ", results$dataset, " of ", results$species)
caption_over <- paste0("Results of the overlap probability random test for the ", results$ataset, " of ", results$species)

## Size differences
kable(make.table(results$differences, "bonferroni"), digits = 5, caption = caption_diff)

## Probability of overlap
kable(make.table(results$overlaps, "bonferroni"), digits = 5, caption = caption_over)

pipeline.plots(results)
```

### Mandible

```{r, fig.width = 10, fig.height = 15, echo = FALSE, message = FALSE}
results <- pipeline.test("Wombat_ursinus", "mandible", "../Data/Processed/", verbose = TRUE)

caption_diff <- paste0("Results of the area difference random test for the ", results$dataset, " of ", results$species)
caption_over <- paste0("Results of the overlap probability random test for the ", results$ataset, " of ", results$species)

## Size differences
kable(make.table(results$differences, "bonferroni"), digits = 5, caption = caption_diff)

## Probability of overlap
kable(make.table(results$overlaps, "bonferroni"), digits = 5, caption = caption_over)

pipeline.plots(results)
```

## Wombat krefftii

### Cranium

```{r, fig.width = 10, fig.height = 15, echo = FALSE, message = FALSE}
results <- pipeline.test("Wombat_krefftii", "cranium", "../Data/Processed/", verbose = TRUE)

caption_diff <- paste0("Results of the area difference random test for the ", results$dataset, " of ", results$species)
caption_over <- paste0("Results of the overlap probability random test for the ", results$ataset, " of ", results$species)

## Size differences
kable(make.table(results$differences, "bonferroni"), digits = 5, caption = caption_diff)

## Probability of overlap
kable(make.table(results$overlaps, "bonferroni"), digits = 5, caption = caption_over)

pipeline.plots(results)
```

### Mandible

```{r, fig.width = 10, fig.height = 15, echo = FALSE, message = FALSE}
results <- pipeline.test("Wombat_krefftii", "mandible", "../Data/Processed/", verbose = TRUE)

caption_diff <- paste0("Results of the area difference random test for the ", results$dataset, " of ", results$species)
caption_over <- paste0("Results of the overlap probability random test for the ", results$ataset, " of ", results$species)

## Size differences
kable(make.table(results$differences, "bonferroni"), digits = 5, caption = caption_diff)

## Probability of overlap
kable(make.table(results$overlaps, "bonferroni"), digits = 5, caption = caption_over)

pipeline.plots(results)
```


## Wombat latifrons

### Cranium

```{r, fig.width = 10, fig.height = 15, echo = FALSE, message = FALSE}
results <- pipeline.test("Wombat_latifrons", "cranium", "../Data/Processed/", verbose = TRUE)

caption_diff <- paste0("Results of the area difference random test for the ", results$dataset, " of ", results$species)
caption_over <- paste0("Results of the overlap probability random test for the ", results$ataset, " of ", results$species)

## Size differences
kable(make.table(results$differences, "bonferroni"), digits = 5, caption = caption_diff)

## Probability of overlap
kable(make.table(results$overlaps, "bonferroni"), digits = 5, caption = caption_over)

pipeline.plots(results)
```

### Mandible

```{r, fig.width = 10, fig.height = 15, echo = FALSE, message = FALSE}
results <- pipeline.test("Wombat_latifrons", "mandible", "../Data/Processed/", verbose = TRUE)

caption_diff <- paste0("Results of the area difference random test for the ", results$dataset, " of ", results$species)
caption_over <- paste0("Results of the overlap probability random test for the ", results$ataset, " of ", results$species)

## Size differences
kable(make.table(results$differences, "bonferroni"), digits = 5, caption = caption_diff)

## Probability of overlap
kable(make.table(results$overlaps, "bonferroni"), digits = 5, caption = caption_over)

pipeline.plots(results)
```

# Between species

### Cranium

```{r, fig.width = 10, fig.height = 15, echo = FALSE, message = FALSE}
results <- pipeline.test("Wombat", "cranium", "../Data/Processed/", verbose = TRUE)

caption_diff <- paste0("Results of the area difference random test for the ", results$dataset, " of ", results$species)
caption_over <- paste0("Results of the overlap probability random test for the ", results$ataset, " of ", results$species)

## Size differences
kable(make.table(results$differences, "bonferroni"), digits = 5, caption = caption_diff)

## Probability of overlap
kable(make.table(results$overlaps, "bonferroni"), digits = 5, caption = caption_over)

pipeline.plots(results)
```

### Mandible

```{r, fig.width = 10, fig.height = 15, echo = FALSE, message = FALSE}
results <- pipeline.test("Wombat", "mandible", "../Data/Processed/", verbose = TRUE)

caption_diff <- paste0("Results of the area difference random test for the ", results$dataset, " of ", results$species)
caption_over <- paste0("Results of the overlap probability random test for the ", results$ataset, " of ", results$species)

## Size differences
kable(make.table(results$differences, "bonferroni"), digits = 5, caption = caption_diff)

## Probability of overlap
kable(make.table(results$overlaps, "bonferroni"), digits = 5, caption = caption_over)

pipeline.plots(results)
```