---
title: "Landmark region difference"
author: "Thomas Guillerme"
bibliography: references.bib
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

```{r, message = FALSE, warning = FALSE}
if(!require(knitr)) install.packages("knitr")
if(!require(xtable)) install.packages("xtable")
source("../Functions/utilities.R")
```

## Rarefied results summary

```{r, echo = FALSE}
get.token <- function(p) {
    if(p > 0.05) {
        return("")
    }
    if(p < 0.05 && p > 0.01) {
        return(".")
    }
    if(p < 0.01 && p > 0.001) {
        return("*")
    }
    if(p < 0.001) {
        return("**")
    }
}

species <- c("Wombat", "Wombat_krefftii", "Wombat_latifrons", "Wombat_ursinus")
datasets <- c("cranium", "mandible")

rounding = 3

results_table <- data.frame(matrix(NA, ncol = length(species)*4, nrow = 6+1))

for(sp in 1:length(species)) {

    for(ds in 1:length(datasets)) {

        ## Extract the results
        load(paste0("../Data/Results/", species[sp], "_", datasets[ds], "rarefied.Rda"))

        ## Summarise the results
        difference <- make.table(results$difference, correction = "bonferroni")
        overlap <- make.table(results$overlaps, correction = "bonferroni")

        ## Fill the table
        if(ds == 1) {
            ## Values
            results_table[2:4, 1+(4*(sp-1))] <- round(difference[,2], digits = rounding)
            results_table[2:4, 3+(4*(sp-1))] <- round(overlap[,2], digits = rounding-1)
            ## Signif
            results_table[2:4, 2+(4*(sp-1))] <- paste0(round(difference[,6], digits = rounding),  sapply(difference[,6], get.token)) # Remove the first component of the paste if only tokens needed
            results_table[2:4, 4+(4*(sp-1))] <- paste0(round(overlap[,6], digits = rounding),  sapply(overlap[,6], get.token))

        } else {
            ## Values
            results_table[5:7, 1+(4*(sp-1))] <- round(difference[,2], digits = rounding)
            results_table[5:7, 3+(4*(sp-1))] <- round(overlap[,2], digits = rounding-1)
            ## Signif
            results_table[5:7, 2+(4*(sp-1))] <- paste0(round(difference[,6], digits = rounding),  sapply(difference[,6], get.token))
            results_table[5:7, 4+(4*(sp-1))] <- paste0(round(overlap[,6], digits = rounding),  sapply(overlap[,6], get.token))
        }
    }
}

## Renaming the table elements
rownames(results_table) <- c("test", paste("Cranium", c(1,2,3)), paste("Mandible", c(1,2,3)))
results_table[1,] <- rep(c("diff", "p", "overlap", "p"), length(species))
colnames(results_table) <- names(unlist(sapply(species, rep, 4, simplify = FALSE)))


##
kable(results_table, digits = 4)
```

```{r, eval = TRUE, echo = FALSE, print = FALSE, results = 'hide'}
path <- "../Manuscript/Tables/"
label_table <- "all_differences_rarefied"
caption_table <- "\"diff\" is the difference in landmark length between the ones from the partition and all the other. \"overlap\" is the probability of overlap between the distribution of the landmark lengths in the partitions and all the other. The p values are adjusted using a Bonferroni-Holm correction. Because of the number of bootstrap pseudo-replicates involved in the test (1000), we lowered our threshold for rejecting H0 to p <= 0.01. Signif. codes: 0 ‘**’ 0.001 ‘*’ 0.01 ‘.’ 0.05 ‘ ’ 1"

textable <- xtable(results_table, caption = caption_table, label = label_table)
cat(print(textable), file = paste0(path, label_table, ".tex"))
```
