---
title: "Heat map plot of changes"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

Some fancy plots for the maximum landmark variation.

## Plots 

### Loading the functions

```{r, message = FALSE, warning = FALSE}
## Loading the libraries (and installing if necessary)
if(!require(devtools)) install.packages("devtools")
if(!require(geomorph)) install.packages("geomorph")
if(!require(dispRity)) install_github("TGuillerme/dispRity")
if(!require(landmarktest)) install_github("TGuillerme/landmark-test")
set.seed(1)
```


### Loading the data

```{r}
## Loading a dataset

#loading the below loads objects called land_data, NOT "wombat"
load("../Data/Processed/wombat.Rda")
AllWombats<-land_data
load("../Data/Processed/wombat_lasiorhinus.Rda")
HN<-land_data
load("../Data/Processed/wombat_krefftii.Rda")
NHNW<-land_data
load("../Data/Processed/wombat_latifrons.Rda")
SHNW<-land_data
load("../Data/Processed/wombat_ursinus.Rda")
CW<-land_data
source("../Functions/utilities.R")

```

The "maximum" and "minimum" specimen:

```{r}
## Procrustes variation ranges
cranium=SHNW$cranium
variation <- variation.range(cranium$procrustes, return.ID = TRUE, CI = 0.5)
specimens_min_max <- variation$min.max
procrustes_var <- variation$range[,1]
```

```{r, eval = FALSE}
gridPar = gridPar(pt.bg = "white", pt.size = 0.5)
open3d()
plotRefToTarget.heat(cranium$procruste$coords[, , specimens_min_max[2]],
                     cranium$procruste$coords[, , specimens_min_max[1]],
                     col = heat.colors, pt.size = 0.3, col.val = procrustes_var,
                     plotRefToTarget.args = list(mag = 1))
```


#Contrasting specimens on opposite PC axes

```{r}
## Procrustes variation ranges



variation_all_PC_axis <- variation.range(cranium$procrustes, return.ID = TRUE, ordination = TRUE, axis = 1)
#This does not work
specimens_min_max <- variation_all_PC_axis$min.max
procrustes_var <- variation_all_PC_axis$range[,1]
```

```{r, eval = FALSE}
gridPar = gridPar(pt.bg = "white", pt.size = 0.5)
open3d()
plotRefToTarget.heat(cranium$procruste$coords[, , specimens_min_max[2]],
                     cranium$procruste$coords[, , specimens_min_max[1]],
                     col = heat.colors, pt.size = 1, col.val = procrustes_var,
                     plotRefToTarget.args = list(mag = 1))
```


#Trying to do this using hypothetical PC min/max landmarks 

```{r, eval = FALSE}

#@params Species_dataset is the dataset in question (e.g.CW$cranium); 
#@params min_or_max_first ("min", "max")is if you want min referenced to max or vice versa. this is handy if one common lm displacement pattern happens to be associated with opposite signed PC scores.


heatplot.PCs<-function (species_dataset,minfirst, PC_axis,...){
  
  ## Procrustes variation ranges for PCA; axis determines which ordination axis to use
  variation <- variation.range(species_dataset$procrustes, return.ID = TRUE, axis=PC_axis, ordination=species_dataset$ordination)
  
  # identifies specimens at opposite ends of the PC spectrum
  specimens_min_max <- variation$min.max
 
   #determines range of variation between PC extremes
    procrustes_var <- variation$range[,1]
    
    #runs PCA for min/max plotting
    PCA=plotTangentSpace(species_dataset$procrustes$coords, verbose=FALSE)
  
  gridPar = gridPar(pt.bg = "white", pt.size = 0.5)
  
  if(minfirst==TRUE){
  open3d()
    plotRefToTarget.heat(PCA$pc.shapes$PC1min,
                       PCA$pc.shapes$PC1max,
                       col = heat.colors, pt.size = 0.7, col.val = procrustes_var,
                       plotRefToTarget.args = list(mag = 1),...)}
  else {
    open3d()
    plotRefToTarget.heat(PCA$pc.shapes$PC1max,
                       PCA$pc.shapes$PC1min,
                       col = heat.colors, pt.size = 0.7, col.val = procrustes_var,
                       plotRefToTarget.args = list(mag = 1), ...)}
}

heatplot.PCs(AllWombats$cranium, minfirst=FALSE, PC_axis=1)
heatplot.PCs(HN$cranium, minfirst=TRUE, PC_axis=1 )
heatplot.PCs(CW$cranium)
heatplot.PCs(SHNW$cranium, minfirst)
heatplot.PCs(NHNW$cranium, minfirst)

heatplot.PCs(AllWombats$mandible, minfirst=FALSE, PC_axis=1)
heatplot.PCs(HN$mandible, minfirst=TRUE, PC_axis=1)
heatplot.PCs(CW$mandible, minfirst=FALSE, PC_axis=1)
heatplot.PCs(SHNW$mandible, minfirst=TRUE, PC_axis=1)
heatplot.PCs(NHNW$mandible, minfirst=TRUE, PC_axis=1)

```

