---
title: "Figures for wombat shape variation paper"
author: "Vera Weisbecker"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---


# Loading the data

```{r, message = FALSE, warning = FALSE}
## Loading the libraries (and installing if necessary)

if(!require(geomorph)) install.packages("geomorph")
source("../Functions/utilities.R")
library(ggplot2)
# Install and load ggConvexHull
library(devtools)
devtools::install_github("cmartin/ggConvexHull")
library(ggConvexHull)
source("../Functions/utilities.R")
set.seed(1)
library(landmarktest)

# load the data

##the below loads the Wombat.Rda from the processed data (i.e. partitions, procrustes data, and ordination results); but the object is NOT called the file name called under "load", it is "land_data"
load("../Data/Processed/wombat.Rda")

#read classifiers
cranium<-read.csv("../Data/Raw/classifier_cranium_wombat.csv")
mandible<-read.csv("../Data/Raw/classifier_mandible_wombat.csv")


```

#Visualize landmark partitions
```{r, message = FALSE, warning = FALSE}
#separate land_data into the relevant components

#Define the partitions (needs to be done individually)
#LandmarkRegions=define.modules(land_data$cranium$procrustes$coords[,,5],2)
#write.csv(LandmarkRegions, file="../Data/Results/additional_snout.csv")

#Optional:
PartNames<-c("Zyg", "Sn", "Oc", "Po", "Rest")# This is not necessary for colouring the cranium AND needs to be separately accessed, but helps in identifying the partitionss

plot.partitions(land_data$cranium)
plot.partitions(land_data$mandible)

#The best way to fine-tune is to plot the coloured regions with the number
plot.partitions(land_data$mandible)
text3d(mshape(land_data$mandible$procrustes$coords), text=c(1:577))

```

# Visualizing shape changes between Principal component extremes
```{r, message = FALSE, warning = FALSE}




PCA.vectors(land_data$cranium, minfirst=TRUE)
```
#PCA plot for Figure
```{r, message = FALSE, warning = FALSE}

Classifiers=list("cranium"=cranium, "mandible"=mandible)
PC=list()

for (i in 1:length(Classifiers)){
  #prep classifiers
  names <- dimnames((land_data)[[i]]$procrustes$coords)[[3]] # Gives all IDs in data
  Species <- as.factor(Classifiers[[i]]$Species)
  Locality <- as.factor(Classifiers[[i]]$Locality)
  Environment <- as.factor(Classifiers[[i]]$Environment) 
  Sex <- as.factor(Classifiers[[i]]$Sex)
  levels(Sex)<-c(levels(Sex),"U")  #Add the extra level to your factor
  Sex[is.na(Sex)] <- "U"           #Change NA to "U"
  levels(Environment)<-c(levels(Environment)," ") 
  Environment[is.na(Environment)] <- " "           #Change NA to "U"
  
  #prep pc scores
  
  PC[[i]] <- data.frame(land_data[[i]]$ordination$x[,1], land_data[[i]]$ordination$x[,2])#Why does this not work??
  
 }
names(PC)<-names(Classifiers)


#outside the loop this works. I think I need to learn MUCH more about how to use selector addresses!
PC[[1]] <- data.frame(land_data[[1]]$ordination$x[,1], land_data[[1]]$ordination$x[,2])
PC[[2]] <- data.frame(land_data[[2]]$ordination$x[,1], land_data[[2]]$ordination$x[,2])




#The below is just sample text, I'll get rid of it when the above works

names <- dimnames(land_data$cranium$procrustes$coords)[[3]] # Gives all IDs in data
Species <- as.factor(cranium$Species)
Locality <- as.factor(cranium$Locality)
Environment <- as.factor(cranium$Environment) 
Sex <- as.factor(cranium$Sex)

WomCrPC1Scores <- land_data$cranium$ordination$x[,1]
WomCrPC2Scores <- land_data$cranium$ordination$x[,2]
WomCrPC <- data.frame(WomCrPC1Scores, WomCrPC2Scores)
levels(Sex)<-c(levels(Sex),"U")  #Add the extra level to your factor
Sex[is.na(Sex)] <- "U"           #Change NA to "U"
levels(Environment)<-c(levels(Environment)," ") 
Environment[is.na(Environment)] <- " "           #Change NA to "U"


plot.new()
#in the below, it doesn't work to use PC$cranium$land_data..i...ordination.x...1. and PC$cranium$land_data..i...ordination.x...2. for x and y - not sure why. It might be easier to just do the PCA manually
ggplot(PC$cranium, aes(x=PC$cranium$land_data..i...ordination.x...1., y=PC$cranium$land_data..i...ordination.x...2., colour=Species, fill=Species))+
  geom_convexhull(alpha=.4)+
  scale_shape_manual(values = c(21, 22, 24))+
  geom_point(aes(shape=Sex, fill=Species), color="black", size=4, stroke = 0.75)+
  geom_text(aes(label=Environment), size=5, hjust=1.35, vjust=0.25, colour="black")+
  labs(x = "Principal component 1", y = "Principal component 2")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position="none",
        axis.text=element_text(size=14), axis.title=element_text(size=16))
theme_set(theme_bw(12))

```
