---
title: "Other analyses"
author: "Vera Weisbecker"
bibliography: references.bib
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

```{r, message = FALSE, warning = FALSE}
## Loading the libraries (and installing if necessary)
if(!require(knitr)) install.packages("knitr")
if(!require(geomorph)) install.packages("geomorph")
source("../Functions/utilities.R")
set.seed(42)

#loading the below loads objects called land_data, NOT "wombat"
load("../Data/Processed/wombat_krefftii.Rda")
NHNW<-land_data
load("../Data/Processed/wombat_latifrons.Rda")
SHNW<-land_data
load("../Data/Processed/wombat_ursinus.Rda")
CW<-land_data

#read classifiers
cranium<-read.csv("../Data/Raw/classifier_cranium_wombat.csv")
mandible<-read.csv("../Data/Raw/classifier_mandible_wombat.csv")

```

#Checking for outliers

```{r, message = FALSE, warning = FALSE}


#set up the gridpars for plotRefToTarget
Points=gridPar(pt.size=0.7)

#Common wombat

##Cranium

###plot the procrustes distances from mean for specimens to identify the ones beyone the upper/lower quartiles

plotOutliers(CW$cranium$procrustes$coords)#CW_M11 (individual 14 is an outlier)

###use plotRefToTarget with lollipop graphs to check if outlier has landmark error; replace number according to which individuals have been identified as outliers
open3d()
plotRefToTarget(CW$cranium$procrustes$consensus, CW$cranium$procrustes$coords[,,14], method="vector", gridPars = Points)#No evidence of landmarking error

##Mandible
plotOutliers(CW$mandible$procrustes$coords)#20, 10 and 11 are outliers
mshapeCW<-mshape(CW$mandible$procrustes$coords)
open3d()
plotRefToTarget(mshapeCW, CW$mandible$procrustes$coords[,,20], method="vector", gridPars = Points) #Slight assymetry in 2 cases but no evidence of landmarking error


#SHN wombat

##Cranium
plotOutliers(NHNW$cranium$procrustes$coords)#NHNW_M11 (individual 21 is an outlier)
mshapeNHNW<-mshape(NHNW$cranium$procrustes$coords)
open3d()
plotRefToTarget(mshapeNHNW, NHNW$cranium$procrustes$coords[,,21], method="vector", gridPars = Points)#No evidence of landmarking errlr

##Mandible
plotOutliers(NHNW$mandible$procrustes$coords)#No outliers


#NHN wombat

##Cranium
plotOutliers(NHNW$cranium$procrustes$coords)#No outliers

##Mandible
plotOutliers(NHNW$mandible$procrustes$coords)#No outliers

```

#Partition Classifiers according to species

```{r, message = FALSE, warning = FALSE}

#@params Full_Classifier_Table_ is the tables of mandibular or cranial classifiers (e.g. read.csv("../Data/Raw/classifier_cranium_wombat.csv")); spp is a vector of species (e.g. c("CW", "SHNW", "NHNW"))


species <- c("CW", "SHNW", "NHNW")
sp_holders <-c("Common wombat", "SHN wombat", "NHN wombat")

##cranium
for (i in 1:length(unique(cranium$Species))){
   
    Class = cranium[cranium$Species == sp_holders[i],]
    
    sp_name=paste(species[i],deparse(substitute(cranium)), "Class", sep="_")#prepare for giving names to outputs
   
     assign(sp_name,Class)
    
    }

##mandible
for (i in 1:length(unique(mandible$Species))){
   
    Class = mandible[mandible$Species == sp_holders[i],]
    
    sp_name=paste(species[i],deparse(substitute(mandible)), "Class", sep="_")#prepare for giving names to outputs
   
     assign(sp_name,Class)
    
    }



```

#Allometry analyse
#Allometry Analyses
```{r, message = FALSE, warning = FALSE}


AllData=list("NHNW"=NHNW, "SHNW"=SHNW, "CW"=CW)

allom_output=list()


for (i in 1:length(AllData)){
  
      for (k in 1:length(AllData[[1]])){
      
      allom_output[i][[k]]=list()
        
      allom_output[[i]][[k]]  <-handle.procD.formula(coords~Csize, AllData[[i]][[k]]$procrustes, procD.fun=procD.allometry, iter=1000)
      
    }

}

names(allom_output)=names(AllData)

names(allom_output[[1]])=names(AllData[[1]])#I can't name "mandible" and "cranium"; this only works if I call allom_output[[1]]separately. A minor issue for later.




```

#Other procD analyses

```{r, message = FALSE, warning = FALSE}

AllData=list("NHNW"=NHNW, "SHNW"=SHNW, "CW"=CW)
AllClassifiers=list("NHNW"=list("cranium"=NHNW_cranium_Class, "mandible"=NHNW_mandible_Class), "SHNW"=list("cranium"=SHNW_cranium_Class, "mandible"=SHNW_mandible_Class),"CW"=list("cranium"=CW_cranium_Class, "mandible"=CW_mandible_Class))

coords_Geo_output=list()
    
    for (i in 1:length(AllData)){
      coords_Geo_output[[i]]=list()
      
      for (k in 1:length(AllClassifiers[[i]])){
        coords_Geo_output[[i]][[k]] <- AllData [[i]][[k]]$procrustes$coords [ , ,as.character(AllClassifiers[[i]][[k]]$Geolocation) == "Yes"]
      }
      names(coords_Geo_output[[i]])<-names(AllData[[i]])
    }

names(coords_Geo_output)<-names(AllData)


################Building blocks of loops - first check that the individual analyses work

    

    
#Separate out the coordinates
coords_Geo_output=list()
    
coords_Geo_output[[2]][[1]] <- AllData [[2]][[1]]$procrustes$coords [ , ,as.character(AllClassifiers[[2]][[1]]$Geolocation) == "Yes"]#This works


coordsMa.SHNW.geo <- SHNWgpa.Ma$coords[ , , SHNWMaClass$Geolocation == "Yes"]#subsetting to only those specimens for which geolocation is available
coordsMa.SHNW.Sex <- SHNWgpa.Ma$coords[ , , !is.na(SHNWMaClass$Sex)]#Subsetting something that has nas. 
SHNWSexMa=SHNWMaClass$Sex[!is.na(SHNWMaClass$Sex)]
csizeMa.SHNW.Sex<-SHNWgpa.Ma$Csize[!is.na(SHNWMaClass$Sex)]
procD.lm(coordsMa.SHNW.geo ~ SHNWMaClass$Aridity)
procD.lm(coordsMa.SHNW.geo ~ SHNWMaClass$Temperature)
procD.lm(coordsMa.SHNW.Sex ~ SHNWSexMa*csizeMa.SHNW.Sex)
procD.lm(coordsMa.SHNW.Sex ~ SHNWSexMa+csizeMa.SHNW.Sex)

summary(lm(csizeCr.SHNW.Sex~SHNWSexCr))
summary(lm(csizeMa.SHNW.Sex~SHNWSexMa))



```
#2-Block Partial Least Squares analysis
##reduce coordinate datasets to only those that have mandibles and crania

```{r, message = FALSE, warning = FALSE}

AllData=list("NHNW"=NHNW, "SHNW"=SHNW, "CW"=CW)
AllClassifiers=list("NHNW"=list("cranium"=NHNW_cranium_Class, "mandible"=NHNW_mandible_Class), "SHNW"=list("cranium"=SHNW_cranium_Class, "mandible"=SHNW_mandible_Class),"CW"=list("cranium"=CW_cranium_Class, "mandible"=CW_mandible_Class))


matched_coords<-reduce.check(AllData, AllClassifiers)
#the below indicates whether cranial and mandibular coord datasets match
matched_coords[[2]]

```
##run 2BPLS code

```{r, message = FALSE, warning = FALSE}
SHNWTBPLS <- two.b.pls(matched_coords[[1]]$SHNW$cranium ,matched_coords[[1]]$SHNW$mandible ,iter=1000) 
summary(SHNWTBPLS)
save(SHNWTBPLS, file="../Data/Results/SHNWTBLS.Rda")
#When run, hash out the above and just load the resutls of the 2Block analysis
load("../Data/Results/SHNWTBLS.Rda")
NHNWTBPLS <- two.b.pls(matched_coords[[1]]$NHNW$cranium ,matched_coords[[1]]$NHNW$mandible, iter=1000) 
 summary(NHNWTBPLS)
save(NHNWTBPLS, file="../Data/Results/NHNWTBLS.Rda")
load("../Data/Results/NHNWTBLS.Rda")
CWTBPLS <- two.b.pls(matched_coords[[1]]$CW$cranium ,matched_coords[[1]]$CW$mandible ,iter=1000) 
 summary(CWTBPLS)
 save(CWTBPLS, file="../Data/Results/CWTBLS.Rda")
load("../Data/Results/CWTBLS.Rda")
 
 
```
##correlate 2BPLS scores with the first 2 principal components for each species
```{r, message = FALSE, warning = FALSE}
CWTBPLS_Cranium_Scores <- as.data.frame(CWTBPLS$XScores[c(1:18)], row.names=dimnames(CWTBPLS$XScores)[[1]])

#the below doesn't work because the ordination in land_data doesn't have pc scoress
CWPC1=as.data.frame(CW$cranium$ordination$scores[,1])

CWCsize=as.data.frame(CW$cranium$procrustes$Csize)

CWPLS_PCA_separate=merge(CWTBPLS_Cranium_Scores,CWPC1,by="row.names",all.x=TRUE)

CWPLS_PCA_inonego<-merge((as.data.frame(CW$cranium$ordination$scores[,1])), (as.data.frame(CW$cranium$procrustes$Csize)))


CWPLS_CPLS=merge(CWTBPLS_Cranium_Scores,CWCsize,by="row.names",all.x=TRUE)#Why can't I merge all three??



plot(CWPLS_PCA[,2], CWPLS_PCA[,3])
summary(lm((CWPLS_PCA[,2]~CWPLS_PCA[,3])))
summary(lm((CWPLS_CPLS[,2]~CWPLS_CPLS[,3])))

 
summary(lm((SHNWPLS_PCA[,2]~SHNWPLS_PCA[,3])))##NOTE PC2 used for SHNW!
summary(lm((SHNWPLS_Csize[,2]~SHNWPLS_Csize[,3])))##NOTE PC2 used for SHNW!
```
